site_name: Generate Article for NW
site_url: https://nw.newknow.net/
theme:
  name: material
  features:
    - content.code.copy
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
nav:
  - Home: index.md
  - Template Tags: template-tags/index.md
